### ISSUE TITLE
Missing automated CI/CD on this repo

### ISSUE THREAD

**Issue by neutrinoceros** [amrvac/amrvac#14]
I find that running the whole test suite by hand can be a massive source of lag in development.
I'm currently in search for a solution to automate the test pipeline on github.

**Comment by neutrinoceros** [comment]
https://travis-ci.org/
seems like everything I'm looking for and more
As I can only deploy it for repos I own, I will fork this one and test it there.

**Comment by neutrinoceros** [comment]
I'm on it. I could deploy Travis on my fork and run all tests there with no effort. Only problem left to solve is that the script currently doesn't recognize failure when a single test fails.

**Comment by neutrinoceros** [comment]
in case you wanna help/are curious about it, here's the current `.yml` file I have

https://github.com/neutrinoceros/amrvac/blob/master/.travis.yml

**Comment by jannisteunissen** [comment]
I think I will only have time in a couple of weeks (I'm mostly traveling for about a month)

**Comment by neutrinoceros** [comment]
In that case I hope this will be a solved problem by then :)
I'll let you know how to do it on this repo one I solved it.

**Comment by neutrinoceros** [comment]
e1e3ca38428e5e108c1d3355df22bfd70b14e34f adds the building status to `README.md`
This commit was meant for the `ci` branch but nevermind, it'll soon be updated.

`ci` includes two new files `.travis.yml` and `tests/test_runner.sh`. I was able to automate the test suite on a separate fork with those.

All that is needed now is giving Travis proper access to the repo. This can only be done through the owner account. I don't know who has access to it.

**Comment by neutrinoceros** [comment]
note that while I was testing this, I discovered that one test in the mhd suite is currently broken. See https://github.com/amrvac/amrvac/issues/15

Additionally, I observe that there are no Makefiles in `tests/nonlinear/`nor in `tests/particle/`. I should be able to add them myself.

**Comment by neutrinoceros** [comment]
Pull request created https://github.com/amrvac/amrvac/pull/16
Now waiting for the build to complete.

**Comment by jannisteunissen** [comment]
I think everything is working now! Thanks a lot for adding this. Shall we close this issue or are further improvement needed?

**Comment by neutrinoceros** [comment]
The only possible problem I'm seeing right now is that I may be the only owner of the travis account.
Not sure though.
In the mean time if you're already able to use it as your own it's okay I think :)
