### ISSUE TITLE
broken mhd test prominence_Rayleigh_Taylor_2.5D

### ISSUE THREAD

**Issue by neutrinoceros** [amrvac/amrvac#15]
While running the whole test suite, I noticed that only one test currently fails on `master`:

`tests/mhd/prominence_Rayleigh_Taylor_2.5D/`

I checked the history and got the following info:
d5809d4 fails to build the test (make fails)
06e9083 build correctly but fails the test itself

those commits are consecutive so I could not get closer to the issue without inspecting the commits themselves. As this concerns a part of the code I'm not at all familiar with, I'll put this issue in the hands of @99xc41 as he seems to be the most recent author on this test.

**Comment by neutrinoceros** [comment]
additional note : last commit affecting this test was ff8d517704a7e6cd04a8536a9aca11772072eb62 and fails it

**Comment by neutrinoceros** [comment]
however, the previous one 0d3c67a302e0c590451f1889c79211f238767d47 passes it

**Comment by neutrinoceros** [comment]
I confirm that ff8d517704a7e6cd04a8536a9aca11772072eb62 is the commit that broke it, as the one just before that, 9112aa7e1e09e1812a87767701f2c109b1674068 passes the test.
The breaking commit is enormous so I won't attempt to find the bug myself.

**Comment by jannisteunissen** [comment]
I've set the 'new' output for this test as the correct one (it looks identical, but NaN's are now gone), so now all tests pass!

**Comment by jannisteunissen** [comment]
Hmm, apparently the test is still failing, I'll have another look at it.

**Comment by jannisteunissen** [comment]
I've now removed the failing test in a103464
