### ISSUE TITLE
geometry info is missing in `.dat` output files 

### ISSUE THREAD

**Issue by neutrinoceros** [amrvac/amrvac#17]
This is already mentionned in
http://amrvac.org/md_doc_fileformat.html

do we have plans for this ? I guess adding info to the header can break existing readers (such as `tools/python/dat_reader.py`) but I guess those could (or should) be able to handle it, at least if we update them at the same time.

**Comment by jannisteunissen** [comment]
We can add more information to the header without breaking backwards compatibility. What kind of information would you precisely like to add?

**Comment by neutrinoceros** [comment]
specifically, I'm thinking about the "geom" parameter used by `set_coordinate_system()`
I'll probably come up with other needs as I go (I'm trying to built support to read amrvac `.dat` files with yt https://yt-project.org/ )

**Comment by neutrinoceros** [comment]
this has been implemented
