### ISSUE TITLE
There is an error when I run the first test. I don't know how to solve it

### ISSUE THREAD

**Issue by YuLiumt** [amrvac/amrvac#19]
I use brew install gcc on my mac to download gfortran
gcc version 8.2.0 (Homebrew GCC 8.2.0)
When i run make -j 4
There is an error :
Undefined symbols for architecture x86_64:
  "_mpi_type_struct_", referenced from:
      ___mod_particle_base_MOD_init_particles_com in libamrvac.a(mod_particle_base.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [amrvac] Error 1
rm mod_usr.o amrvac.f amrvac.o
 I don't know how to solve it

**Comment by YuLiumt** [comment]
I solve this problem. The error happens in my openmpi. I use the source to install it. when I use brew install open-mpi, Then its OK

**Comment by jannisteunissen** [comment]
Great! I'll close this issue then.
