### ISSUE TITLE
Deprecated and removed OpenMPI prototypes

### ISSUE THREAD

**Issue by OliverLew** [amrvac/amrvac#26]
I ran into this issue when preparing amrvac for Prof. Keppens' class. This should be the same problem as #19 , but I think it's better to open a new issue here.

The removed prototypes like `MPI_TYPE_STRUCT` will cause compilation error for openmpi version 4.0.0 (the latest version atm). At first I want to inform you of this, but then I saw the commit here https://github.com/amrvac/amrvac/commit/a642cdcd91c53cc8869f4514fe58fcb3257bb2fb . You had changed this before but rolled it back again to support old versions of mpi.

Can this be solved for both old and latest/future versions of openmpi (maybe some preprocessing)?

(For now two workarounds for me is either downgrade to a previous version of openmpi or manually change the source code.)

**Comment by jannisteunissen** [comment]
Perhaps we could start by having a branch with the new style MPI calls. This should already work under MPI 2 I think, so if it works for the majority of users we can make it the new default (and have another branch with the old style MPI calls).

**Comment by OliverLew** [comment]
Revisiting this issue, after two years, since I am using amrvac, again :). It seems that openmpi added back the deprecated things in 4.0.x even just before when I created this issue, see https://github.com/open-mpi/ompi/issues/6114. I confirmed that's gone in openmpi version 4.0.5 today, so I will close this issue now.
