### ISSUE TITLE
Make sure all the tests run with ARCH=debug

### ISSUE THREAD

**Issue by jannisteunissen** [amrvac/amrvac#28]
Some of the tests currently have problems, mostly with HLLC it seems, for example:

`amrvac/tests/mhd/rotor_2D:
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
Backtrace for this error:
#3  0xD916D9 in __mod_mhd_hllc_MOD_mhd_get_lcd at mod_mhd_hllc.f:133 (discriminator 1)
`

**Comment by neutrinoceros** [comment]
Hi Jannis, it is still an issue and do you need help with it ?

**Comment by jannisteunissen** [comment]
Not sure, you can try it out with 'make ARCH=debug' in the tests folder

**Comment by 99xc41** [comment]
All the tests are now passed with ARCH=debug compilation since Aug 17, 2021.
