### ISSUE TITLE
Strange behaviour with Intel compiler on VSC cluster

### ISSUE THREAD

**Issue by n-claes** [amrvac/amrvac#29]
When compiling using `setup.pl -d=2` followed by `make`  and `mpirun`, everything works fine on the VSC cluster.
However, when compiling with the intel option `setup.pl -d=2 -arch=intel` for the simple `tests/rho/vac` test case, strange behaviour occurs when running the executable. The startup info gets printed multiple times (as many times as there are processors selected, actually) after which program execution terminates following a `forrtl: CLOSE error` trying to close a file writen to `unit -129` (which I can not find anywhere).

The 0000 .dat and .vtu files are present, the .log file however is not. See attached file for detailed error log and reproduction of the issue.
[amrvac_crash_intel.txt](https://github.com/amrvac/amrvac/files/3492586/amrvac_crash_intel.txt)

VSC modules loaded are `intel/2018a`, `GCC/6.4.0-2.28` and `OpenMPI/2.1.2-GCC-6.4.0-2.28`.

**Comment by jannisteunissen** [comment]
It's not a good idea to mix Intel and GCC as you are doing now. Instead try this:

- module purge
- module load intel
- make (you can use -j / ARCH=intel)

This works on brEniac and probably also on other clusters.

**Comment by n-claes** [comment]
Thanks Jannis, that was indeed the problem, everything works as expected if only the intel module is loaded. Works both on BrEniac and the new Thinking, closing the issue.
