### ISSUE TITLE
error in import path for python documentation

### ISSUE THREAD

**Issue by FinMacDov** [amrvac/amrvac#30]
For the python documentation (amrvac.org/md_doc_python_datfiles.html), the import path for reading dat files should be:

from amrvac_tools.datfiles.reading import amrvac_reader

**Comment by n-claes** [comment]
Indeed, you're right! Small oversight from my part, just pushed the fix to the master branch [#1578](https://github.com/amrvac/amrvac/commit/b30eb6010d5b4c23ae917ead7a2f976db310593c).
