### ISSUE TITLE
Python coding style

### ISSUE THREAD

**Issue by FinMacDov** [amrvac/amrvac#33]
I have a question with regards to changes to python tools. When people are suggesting edits do you want us to follow a certain coding style like PEP 8 or use tools that automatically format code like Black?

**Comment by n-claes** [comment]
Well it is always useful to follow some sort of convention, I personally use PEP 8 as a _guideline_ but not as a strict rule. As long as the code is clean and readable, and all variable/method/class names have clear distinctions (but this last point is quite subjective) everything is fine!

**Comment by neutrinoceros** [comment]
Ah, here's my take on this:
https://github.com/FinMacDov/amrvac/commit/90a6c9fa011e33629cad229960fe54d1824448c9
