### ISSUE TITLE
Discussion: AMRVAC 2.2 and branch separations

### ISSUE THREAD

**Issue by neutrinoceros** [amrvac/amrvac#39]
Today @jannisteunissen commited a "hotfix" to the master branch, fixing a just-discovered bug with the restart feature. The bug however is still present in the 2.2-testing branch.
  
I would think that merging master into 2.2-testing is okay, but if I remember correctly, @jannisteunissen mentioned that this could lead to undesirable overhead last time we discussed it.

In a fully developped branching model, hotfixes would look like this
https://nvie.com/posts/a-successful-git-branching-model/#hotfix-branches

In that model, the master branch should always contain production ready code (which is desirable), and hotfixes can easily be propagated to development branches (2.2-testing is such a branch) because they originally happen on separate branches of their own.

In time, I believe enforcing such a development discipline would be beneficial.
For now, I'm sure there are ways we can propagate this specific hotfix to the development branch without causing potential conflicts in the future, but I'd like to get some inputs : why is merging master into 2.2-testing a bad idea ?

**Comment by jannisteunissen** [comment]
I think it's fine to merge the master branch into 2.2-testing in this case. You could also 'cherry-pick' the commit with the fix.

If two branches make changes to the same pieces of code (or functionality), then the order in which you merge becomes more important, but here that is no issue.
