### ISSUE TITLE
doc: datfile format page is incomplete

### ISSUE THREAD

**Issue by neutrinoceros** [amrvac/amrvac#40]
I recently updated this documentation page https://github.com/amrvac/amrvac/blob/master/doc/fileformat.md

and just noticed that the end of the page is not displayed on the website currently.
http://amrvac.org/md_doc_fileformat.html

**Comment by neutrinoceros** [comment]
https://github.com/amrvac/amrvac/commit/29eb29db88f8353633c890fc4c89fdb61ca36273
probably fixed it. @jannisteunissen , do you know what frequency the website builds from the master branch ?

**Comment by jannisteunissen** [comment]
Every night at 6 AM. I can increase it if you want.

**Comment by neutrinoceros** [comment]
No need, but good to know.

**Comment by neutrinoceros** [comment]
fixed
