### ISSUE TITLE
yt docs: images are broken

### ISSUE THREAD

**Issue by neutrinoceros** [amrvac/amrvac#41]
In e78809af14cfe2b2458f9374fe3867de9e03b556, @n-claes added documentation for yt+AMRVAC. The automatic build last night seems to have worked except for images.

@jannisteunissen, do you know what's wrong with the way images were stored ? If it helps, could you increase the build frequency for today so we can iterate a bit ? Thanks

**Comment by n-claes** [comment]
This should be fixed in 9f50714. Apparently when adding images directly using a html tag, Doxygen looks for the `figmovdir` folder _inside_ the `html` directory (which is not there). Adding them by linking to the parent folder through `src='../figmovdir/'` (instead of doing `src='figmovdir/'`) seems to work.

@jannisteunissen, could you trigger a manual update of the website?

**Comment by n-claes** [comment]
Update: this was **NOT** fixed in 9f50714... working on it.

**Comment by n-claes** [comment]
Fingers crossed, e94f15c should do it (99% sure)

**Comment by n-claes** [comment]
e94f15c indeed fixed the broken yt docs figures. For future reference: the original problem was that the figures were too big, so had to limit their size somehow.
I could not find how to do this using pure markdown syntax, so I switched to html notation by doing
```
<img src="figure.png" width="75%"/>
```
but apparently this does _not_ copy the figure itself into the html directory when running Doxygen so it couldn't be found.
Final solution was limiting the maximum allowed figure size directly to 99% page width in the `my_customdoxygen.css` style sheet, then adding the figures using markdown syntax and finally wrapping them in a separate container where I could override their width:
```
 <div style='width: 75%'>
     ![](figmovdir/figure.png)
 </div>
```
By extension, this notation will now also work on all other webpages to control figure style aspects.
@jannisteunissen if you know of a better way to achieve this please let me know, closing this issue for now.
