### ISSUE TITLE
No warning message when number of blocks along some dimension >32 

### ISSUE THREAD

**Issue by NorbertMagyar** [amrvac/amrvac#43]
Hi!
Took some time to figure out that you apparently cannot have more than 32 blocks along a dimension at level 1 (at least in 3D spherical, along r). The run just stalls without error. I haven't tested it for other dimensions/directions. A warning message would be great!

Cheers,

Norbert

**Comment by 99xc41** [comment]
Hi Norbert, I will look into this problem.

**Comment by 99xc41** [comment]
The one-level run with more than 32 blocks in 3D creates 64^3 blocks for Morton curve calculation. The algorithm for removing out-of-domain blocks was not efficient. So the run was very very slow and looks like a halt.  I have changed the algorithm and got 8 times faster than it was.
