### ISSUE TITLE
Compilation issues due to the VACPP

### ISSUE THREAD

**Issue by n-claes** [amrvac/amrvac#45]
I'm running into compilation errors when trying to compile the code. The issue is that the VAC preprocessor breaks continuation lines and inserts an additional `&` on the next line, followed by a line break. This returns an empty line with only an ampersand character `&`, resulting in the Fortran compiler throwing 
`f951: Warning: '&' not allowed by itself in line 542` 
followed by multiple errors and the compilation stops. Below is an example for `mod_geometry.f` in `lib/2d_default`:

<img width="608" alt="Screenshot 2020-03-04 at 10 18 35" src="https://user-images.githubusercontent.com/43474374/75863911-835b5300-5e01-11ea-8715-b9881e0a9418.png">

I can fix it by manually modifying the corresponding line in the `.t` file through insertion of a continuation character in the proper place, but this issue pops up in quite some files meaning that I would have to go through each one of them, modify them, and do it again if I update the code.

Increasing the `maxlen` value in the `vacpp.pl` file also fixes some issues but introduces new ones in other files... Seems to me that this could be fixed by some additional checks in the preprocessor?

@jannisteunissen or @99xc41, any thoughts on this?

Running `perl v5.30.1` and `gfortran 9.2.0` on macOS. Already tried downgrading perl to 5.18 and gfortran to 8.3 but having the same issue.

**Comment by jannisteunissen** [comment]
I assume this a problem that appears when you change some code, not something that is specific to your computer? I'm not a fan of our current preprocessor, to say the least, but that it puts a single `&` on a line is probably something that can easily be fixed. Do you have an example of file that fails?

**Comment by n-claes** [comment]
Well the thing is that I'm compiling the _**source code**_, not a `mod_usr.t` file. I go straight in the `$AMRVAC_DIR/lib` folder and compile.
Typing `make 1d` works without issues, but `make 2d` (and 3d) fails due to the lines becoming longer when the syntax is expanded.
Hence the issue, if it was a plain `mod_usr.t` file I could just add some additional line breaks, but this is the source code itself. The screenshot that I added above is the processing result of `mod_geometry.t` in the `src` directory.

I would also think that this is a straightforward fix but haven't found anything yet. I'm assuming that it's maybe a perl version issue, but downgrading didn't help.

**Comment by jannisteunissen** [comment]
I've made a few changes to `vacpp.pl` in the branch https://github.com/amrvac/amrvac/tree/vaccpp_test -- can you give it a try?

**Comment by n-claes** [comment]
Just checked out the branch and tried to recompile, but still no luck.
Having the exact same issue -- a single `&` on an empty line after a line break, at the same places as before.

**Comment by jannisteunissen** [comment]
And this is on the master branch? Which OS / Perl version are you using?

**Comment by n-claes** [comment]
Yes, I'm on master. It's no doubt a version issue, compiling on my linux desktop works fine.
Running macOS Catalina with perl v5.30.1

**Comment by n-claes** [comment]
Hi @jannisteunissen, I don't know if there has been any progress on this, but I was unable to fix this issue. I tried multiple versions of perl and various edits to `vacpp.pl` but without any luck.

Because this was really bugging me I simply worked around the issue by writing a python script that checks the `.f` files after they passed through the VACPP preprocessor and corrects them where necessary. I added this to the makefile so it runs automatically, and now everything compiles and runs as it should.

I pushed it to my personal fork since I'm not sure if it is a good idea to include this 'hack' in the main repository. I'm going to keep this issue open for future reference, but for now I have a temporary fix.

**Comment by jannisteunissen** [comment]
I haven't looked into it further, but have you tried using the same Perl version as on your desktop? (E.g. 5.28.1).

**Comment by jannisteunissen** [comment]
By the way 5.28 is also the latest version I see at https://www.perl.org/get.html#unix_like -- so perhaps there is some issue with 5.30. I can't reproduce your error with 5.28, even when I change the maxlen parameter in the vacpp script.

**Comment by n-claes** [comment]
I tried compiling using perl 5.18, 5.28 and 5.30 but always getting the same problem. Since compiling works perfectly on my linux desktop I'm assuming it's a platform-dependent issue with perl, I guess. I should check with other mac users running the same perl version if they are facing similar problems.

The single `&` on a line is not the only issue I'm facing by the way. Additional errors get introduced, like leading commas where there shouldn't be any, trailing ampersands followed by a white line, missing ampersands, etc. So it's not just a 'bad' breakup of the lines, but rather a plain compilation mess-up of the entire file.

Anyway, I managed to fix it for now, maybe a future update of perl fixes the issue.

**Comment by jannisteunissen** [comment]
In that case, I suspect there could be an issue with file encodings, but it's a little surprising other with a Mac have not run into them. Just to be sure, if you clone a new copy of the `amrvac` repository, you get the same errors?

**Comment by n-claes** [comment]
Strangely enough, a fresh clone of the amrvac repository fixed the issue! Don't get any errors when compiling (using perl 5.30). No idea what went wrong with the clone I had and I'm a little confused as to why it suddenly works now, but thanks!
