### ISSUE TITLE
Small dt

### ISSUE THREAD

**Issue by slahabdellaoui** [amrvac/amrvac#46]
Hi everyone, 
I am trying to simulate a model with an external force and special boundary conditions, I am getting small values for dt, I changed CFL and made dt_min=1e-20 or low but it runs with very low dt and crashes after that.
Any suggestions please.

**Comment by 99xc41** [comment]
Improper initial conditions and/or boundary conditions may cause extremely large flow speed and/or huge Alfven speed which makes dt to small to run.
