### ISSUE TITLE
IMEX_Midpoint

### ISSUE THREAD

**Issue by NMoens** [amrvac/amrvac#49]
Hello,

Is it possible that there is a typo in the advect subroutine in mod_advance.t? In the IMEX_mipoint scheme, I think the implicit step is only executed for half a timestep (and it is called only once):

          call global_implicit_update(half,global_time+half*dt,ps2,ps1)

Cheers,
Nicolas Moens

**Comment by n-claes** [comment]
Hi @NMoens, a few hours ago there were some changes to the IMEX schemes pushed to the master branch. Can you check if the issue is still there in the latest version?

**Comment by NMoens** [comment]
Hi @n-claes, the issue is still present (on line 157 of mod_advance.t) in the latest version.

**Comment by ronykeppens** [comment]
IMEX_Midpoint is correctly implemented, it is indeed only calling global_implicit_update once, with half the time step.
Details are in the notes I wrote. During the step ps<--ps+2(ps2-ps1), we add the implicit part with step Dt.
