### ISSUE TITLE
hd_gamma set to 1 when no hd_energy

### ISSUE THREAD

**Issue by Ileyk** [amrvac/amrvac#50]
We have many test cases where the energy equation is not solved (i.e. hd_energy=.false.) but where the thermal pressure is deduced from a polytropic approximation (which is different from the isothermal approximation). Consequently, the new line in mod_hd_phys.t at the beginning of subroutine hd_phys_init which sets hd_gamma to 1 when hd_energy=.false. prevents many configurations from being ran. Is there any reason why this was modified, for instance because of compatibility issues with other modules?

**Comment by Ileyk** [comment]
After tracing back the origin of the change (thanks to Niels!), it looks like it has something to do with this commit made early August for the TRAC method: https://github.com/amrvac/amrvac/commit/1c19eaf1dbbd80fc4ec058f35439a8f7dac218ed. Is hd_gamma=1 when hd_energy=.false. necessary for the TRAC method?

**Comment by 99xc41** [comment]
No. hd_gamma can be more than 1 and assigned with different values in hd_list of par file. TRAC method needs to solve energy equation and hd_gamma=1 is removed in the latest version.
