### ISSUE TITLE
hllc integrator breaks with `hd_dust=.true.`

### ISSUE THREAD

**Issue by neutrinoceros** [amrvac/amrvac#8]
I have no clue what's wrong here. I'll use `hll` meanwhile, and probably will put a mpistop in the code to forbid that case while it's being fixed.

**Comment by neutrinoceros** [comment]
@99xc41, @jannisteunissen or @ronykeppens , this is not a pressing question, but would you happen to know if this is indeed a bug or  if there's an intrinsic limitation to the hllc solver that prohibits using mutlifluids (or pressure less fluids) at the same time ?

**Comment by 99xc41** [comment]
hllc integrator is now not working with dust. We plan to make it working with dust.

**Comment by 99xc41** [comment]
Now the hllc solver is working with dust in HD since Sept 14, 2021. The dust density and momentum are solved with hll flux while gas variables are solved with hllc flux.

**Comment by neutrinoceros** [comment]
Thanks @99xc41 !
